spring:
  application:
    name: authentication-project

  datasource:
    url: jdbc:mysql://localhost:3306/db_authentication?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: ${ENV_DB_USER}
    password: ${ENV_DB_PASSWORD}

  jpa:
    show-sql: true

    hibernate:
      ddl-auto: none

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${ENV_EMAIL_USERNAME}
    password: ${ENV_EMAIL_PASSWORD}

    properties:
      smtp:
        auth: true

        starttls:
          enable: true

server:
  port: 8080

api:
  security:
    token:
      secret: ${ENV_TOKEN_SECRET}

google:
  oauth:
    client:
      id: ${ENV_GOOGLE_CLIENT_ID}
      secret: ${ENV_GOOGLE_CLIENT_SECRET}